engines:
  eslint:
    enabled: true
  tslint:
    enabled: true
    config: tslint.json
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - BUG
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  scss-lint:
    enabled: true
  shellcheck:
    enabled: false
ratings:
  paths:
  - libs/**
  - "**.css"
  - "**.scss"
exclude_paths:
- "angular-modal-gallery"
- "*.ngfactory.ts"
- "*.ngsummary.json"
- "**/dist"
- "**/aot"
- "**/.awcache"
- "**/dll"
- "angular-modal-gallery"
- "src/angular-modal-gallery/"
- "docs"
- "coverage"
- ".scannerwork/"
- "/reports/"
- "examples/**/*.*"
- "**/*.log"
- "**/e2e/"
- "src/**/*.spec.ts"
