engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - BUG
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  scss-lint:
    enabled: true
  shellcheck:
    enabled: false
ratings:
  paths:
  - src/**
  - "**.css"
  - "**.scss"
exclude_paths:
- "docs"
- "**/*.log"
- "e2e/"
- "config/"
- "assets/"
- "demo"
- "dist"
- "rollup.config.js"
- "systemjs.config.js"
- "src/typings.d.ts"
- "src/**/*.spec.ts"
