language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "6.3"
os:
  - linux
 # - osx
env:
  global:
    - secure: Ls1/kwkAqKK5PDuiOqbUo6Tp1oikvk3lKDZ87KqTQuvYMf6g5j+VrLxHkJGiWA8q8oCXfS4qThBxW4gRRgIRvK0/mKEgATC7Em6zthEgZilWXD791dIvFnaALO0dZgSxvkZfd8HlYPgyK73XhRgY/zUPsRD9F9vI/G3STtcXFl28lNMciU/wLnAZsfrOoxh0G6rfqKOLZlEHQ3Vq8Ql/+hYoDAcZYGVsJqJWbkOyJEW6tg6OCzu45yLKq4mh4igoxXAhVwAcMaa/ooAA67qPEBnPuI32z/tf1vfPYXHiq/xvE8u/CRwW2+nthlHr1DD1mIlBASF9/hqRydMNAO+mWOclibM3gTrymWi0QxnK2lpwsM7qMMRjjYWqepN91aZC9aTd5BVHXaKeohRyxzisDbSXqxH/2KOBrxxNA6y3NPi0bs24FPRQjrrbaUEDryp7UeGr/QR4oAS5uOjNywwNXgRZ0Oe9lG6JDf2i+BDj+PsxOg+q87ut1k2/Ug6L2g5GjyDw7OlT7xPH8PXbE11qFRwJTaeKnYed+RTF1Dz4XRgbq8eq6hFP8CDbyAK8dUIUyK6SYNTERmVP7mDNc9REcCr35j79Yuwx894FVb4pSWwYb0dS4t3Aqd0XRYb9uUh09hsPjHgltleum/1ZzgEbR6Nh1BPtbN2ZncP2wGVCW4A= # CODECLIMATE
    - secure: UwHqm091GWX/9rkj6QznO8BQV8V/H80kYNDy94Y1AiTTMnnbbcHcGfDEsLTsInr7CDiVj4brEAOfl6517NHBouFAHWfjw6lXLdX8KOl0WnD7AWkh1oiVQo9XL5CkqA3lA4DrL0fJNkmlh6z3pCmM0igMNFnmNMnkUn3OfqDoa+U/pb+V5sJ6/q4BaCQFMVSbtjwXW87C6NJQXwy8ccQJleNgumpvAf33iYSMOk1VwOVqFg5+LGuFFv4a9Z4PFlDR+FtnNI2uuEycNYHs4d91lIRZFUyZOxShUsl08D+48BQ8uyIuN5d6uyRjFCU0XQiOq3DeJM1nwpO9zSfvYcpd5SUQ/dItr0bxsZboiy7quM1wdj/0Ipw/FEQ2EcRqbiaWTGnTRdq1KQamhu6figF8gT0hY2nN27mSlRJgcFX5bBcW6+UV2RvJvOodLWAyuOWR9S6BA8rm1HZX923FYXtabcFOegQKB5bDkNH7mQ5L62pyTKU5YzSz4VLziMtQQPQKnZDaaMsyxCRt8a7Itf9sjawdQpoDfBCmx9RhpMXh6evYh0TCFpaXne5QswPL4uZL/vtTRAuUTuIU6r9AgXqFbjq6CDWR0/eUxMBRGJWarSeLB/ZlyAg14bslBnVJnyK/SCHll3t18VtPz5w+iNAdGkz1HswyBZCeowrRmJinCMI= # COVERALLS
before_install:
  - bash travisci/before_install.sh
sudo: required
addons:
  firefox: latest
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  #- bash travisci/before_script.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - bash travisci/travis_script.sh
after_success:
  - bash travisci/after_success.sh
#branches:
#  only: master
cache:
  apt: true
  bundler: true
  directories:
    - node_modules